#:tombi schema.strict = false

[tools]
bun = "latest"
"cargo:cargo-cache" = "latest"
deno = "latest"
"github:Willxup/cpa-usage-keeper" = "latest"
"github:anthropics/claude-code" = "latest"
"github:apple/pkl" = "latest"
"github:astral-sh/uv" = "latest"
"github:aubepkg/aube" = "latest"
"github:ggml-org/llama.cpp" = "b11101"
"github:hatoo/oha" = "latest"
"github:jdx/pitchfork" = "latest"
"github:jqlang/jq" = { version = "latest", rename_exe = "jq" }
"github:mikefarah/yq" = { version = "latest", rename_exe = "yq" }
"github:nubjs/nub" = "latest"
"github:pnpm/pnpm" = "latest"
"github:router-for-me/CLIProxyAPI" = "latest"
"github:rs/curlie" = "latest"
"github:sharkdp/bat" = "latest"
"github:sharkdp/fd" = "latest"
"github:showwin/speedtest-go" = "latest"
"github:svenstaro/miniserve" = "latest"
"github:watchexec/watchexec" = "latest"
java = "latest"
node = "latest"
"npm:@vscode/vsce" = "latest"
"npm:npkill" = "latest"
"npm:nrm" = "latest"
"npm:prettier" = "latest"
"npm:skills" = "latest"
"npm:vite-plus" = "latest"
"pipx:hf" = "latest"
python = ["latest", "3.13", "3.11", "3.10"]
ruby = "latest"
rust = "stable"
usage = "latest"

[settings]
auto_update = true
auto_install = false
experimental = true
idiomatic_version_file_enable_tools = ["node", "python", "ruby", "java"]
trusted_config_paths = ["/"]
npm.package_manager = "auto"
minimum_release_age = "0"
fetch_remote_versions_cache = "0"
activate_aggressive = true
system_packages.managers = ["brew", "brew-cask"]
dotfiles.root = "~/.config/mise/.dotfiles"
dotfiles.default_mode = "copy"
env_shell_expand = true
registry_floating = true
history.sync = "sync"
env_conf_d = true

[env]
_.file = { paths = ["~/.config/mise/env/.env"], tools = true }

[dotfiles]
"~/.zshenv" = { mode = "copy" }
"~/.zprofile" = { mode = "copy" }
"~/.zshrc" = { mode = "copy" }
"~/.config/starship.toml" = { mode = "copy" }
"~/.gitconfig" = { mode = "copy" }
"~/.gitignore_global" = { mode = "copy" }
