#:tombi schema.strict = false

[tools]
bun = "latest"
"cargo:cargo-cache" = "latest"
deno = "latest"
"github:BurntSushi/ripgrep" = "latest"
"github:FiloSottile/mkcert" = "latest"
"github:Willxup/cpa-usage-keeper" = "latest"
"github:anthropics/claude-code" = "latest"
"github:apple/pkl" = "latest"
"github:astral-sh/uv" = "latest"
"github:aubepkg/aube" = "latest"
"github:bootandy/dust" = "latest"
"github:cargo-bins/cargo-binstall" = "latest"
"github:cli/cli" = { version = "latest", rename_exe = "gh" }
"github:evilmartians/lefthook" = { version = "latest", rename_exe = "lefthook" }
"github:ggml-org/llama.cpp" = "b10868"
"github:hatoo/oha" = "latest"
"github:jqlang/jq" = { version = "latest", rename_exe = "jq" }
"github:mikefarah/yq" = { version = "latest", rename_exe = "yq" }
"github:nubjs/nub" = "latest"
"github:pnpm/pnpm" = "latest"
"github:router-for-me/CLIProxyAPI" = "latest"
"github:rs/curlie" = "latest"
"github:sharkdp/bat" = "latest"
"github:sharkdp/fd" = "latest"
"github:showwin/speedtest-go" = "latest"
"github:svenstaro/miniserve" = "latest"
"github:watchexec/watchexec" = "latest"
java = "latest"
node = "latest"
"npm:@vscode/vsce" = "latest"
"npm:npkill" = "latest"
"npm:nrm" = "latest"
"npm:prettier" = "latest"
"npm:skills" = "latest"
"npm:vite-plus" = "latest"
"pipx:hf" = "latest"
"pipx:mlx-lm" = "latest"
"pipx:modelscope-hub" = "latest"
python = ["latest", "3.11", "3.10"]
ruby = "latest"
rust = "stable"
usage = "latest"

[bootstrap.packages]
"brew:bash" = "latest"
"brew:ffmpeg" = "latest"
"brew:git" = "latest"
"brew:gnupg" = "latest"
"brew:helm" = "latest"
"brew:k9s" = "latest"
"brew:kubernetes-cli" = "latest"
"brew:mole" = "latest"
"brew:openssl@3" = "latest"
"brew:opus" = "latest"
"brew:python-build" = "latest"
"brew:ruby-build" = "latest"
"brew:starship" = "latest"
"brew:swift-format" = "latest"
"brew:tokei" = "latest"
"brew:witr" = "latest"
"brew:xcbeautify" = "latest"
"brew:zinit" = "latest"
"brew-cask:apifox" = "latest"
"brew-cask:betterdisplay" = "latest"
"brew-cask:brave-browser" = "latest"
"brew-cask:cleanmymac" = "latest"
"brew-cask:cleanmymac-cli" = "latest"
"brew-cask:cleanshot" = "latest"
"brew-cask:crossover" = "latest"
"brew-cask:dbx" = "latest"
"brew-cask:downie" = "latest"
"brew-cask:equinox" = "latest"
"brew-cask:font-maple-mono-nf-cn" = "latest"
"brew-cask:jetbrains-toolbox" = "latest"
"brew-cask:keka" = "latest"
"brew-cask:launchos" = "latest"
"brew-cask:markdown-preview" = "latest"
"brew-cask:mole-app" = "latest"
"brew-cask:ogdesign-eagle" = "latest"
"brew-cask:parallels" = "latest"
"brew-cask:permute" = "latest"
"brew-cask:popclip" = "latest"
"brew-cask:proxyman" = "latest"
"brew-cask:qq" = "latest"
"brew-cask:sf-symbols" = "latest"
"brew-cask:stash" = "latest"
"brew-cask:steam" = "latest"
"brew-cask:syntax-highlight" = "latest"
"brew-cask:tablepro" = "latest"
"brew-cask:telegram" = "latest"
"brew-cask:tencent-meeting" = "latest"
"brew-cask:visual-studio-code" = "latest"
"brew-cask:wechat" = "latest"
"brew-cask:wechatwebdevtools" = "latest"
"brew-cask:wechatwork" = "latest"
"brew-cask:zcode" = "latest"
"brew-cask:zed" = "latest"

[settings]
auto_update = true
auto_install = false
experimental = true
idiomatic_version_file_enable_tools = ["node", "python", "ruby", "java"]
trusted_config_paths = ["/"]
npm.package_manager = "auto"
npm.shell_out = true
minimum_release_age = "0"
fetch_remote_versions_cache = "0"
activate_aggressive = true
system_packages.managers = ["brew", "brew-cask"]
dotfiles.root = "~/.config/mise/.dotfiles"
dotfiles.default_mode = "copy"
env_shell_expand = true
registry_floating = true
history.sync = "sync"
env_conf_d = true

[env]
_.file = { paths = [
  "~/.config/mise/env/github.yaml",
  "~/.config/mise/env/rust.yaml",
  "~/.config/mise/env/npm.yaml",
  "~/.config/mise/env/k9s.yaml",
  "~/.config/mise/env/modelscope.yaml",
  # "~/.config/mise/env/deepseek.yaml",
  # "~/.config/mise/env/xiaomi.yaml",
  # "~/.config/mise/env/z.ai.yaml",
  "~/.config/mise/env/hf.yaml",
  "~/.config/mise/env/tavily.yaml",
  "~/.config/mise/env/exa.yaml",
  "~/.config/mise/env/tinyfish.yaml",
  "~/.config/mise/env/hermes-agent.yaml",
  "~/.config/mise/env/claude.yaml",
], expand = true }

_.path = { paths = [], tools = true }

[dotfiles]
"~/.zshenv" = { mode = "copy" }
"~/.zprofile" = { mode = "copy" }
"~/.zshrc" = { mode = "copy" }
"~/.config/starship.toml" = { mode = "copy" }
"~/.gitconfig" = { mode = "copy" }
"~/.gitignore_global" = { mode = "copy" }
