# [install]
# # where `bun install --global` installs packages
# globalDir = "~/.bun/install/global"
# # where globally-installed package bins are linked
# globalBinDir = "~/.bun/bin"
# # set default registry as a string
# registry = "https://registry.npmjs.org"

# [install.cache]
# # the directory to use for the cache
# dir = "~/.bun/install/cache"
